name: Ezyw App Sample CI Checker

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  ezyw_sample_app_protocol_check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: |
        ./gradlew test
        ./gradlew build
        #./gradle connectedCheck
        #./gradlew connectedAndroidTest
